#include <stdio.h>
#include <stdlib.h>
#include <iostream>
#include <string>
#include <sstream>

using namespace std;

#include "lib_trie.h"

int main(int argc, char * argv[]) {
	
	//char * palavra = argv[1];
	string palavra =  "ACGATTACAGATTACAGATTACAAAAGCAAACACACACACACAGGGT";
	//cout << palavra << " tamanho: " << palavra.length() << endl;
	string palavra2 =  "ACGGT";
	//cout << palavra2 << " tamanho: " << palavra2.length() << endl;
	string palavra3 =  "ACGATTACAGATTACAGATTACAAAAGCAAACACACACACACAGGGTACGATTACAGATTACAGATTACAAAAGCAAACACACACACACAGGGT";
	//cout << palavra3 << " tamanho: " << palavra3.length() << endl;
	//string palavra4 =  "ACGATTACAGATTACAGATTACAAAAGCAAACACACACACACAGGGTACGATTACAGATTACAGATTACAAAAGCAAACACACACACACAGGGTACGATTACAGATTACAGATTACAAAAGCAAACACACACACACAGGGTACGATTACAGATTACAGATTACAAAAGCAAACACACACACACAGGGTACGATTACAGATTACAGATTACAAAAGCAAACACACACACACAGGGTACGATTACAGATTACAGATTACAAAAGCAAACACACACACACAGGGTACGATTACAGATTACAGATTACAAAAGCAAACACACACACACAGGGTACGATTACAGATTACAGATTACAAAAGCAAACACACACACACAGGGTACGATTACAGATTACAGATTACAAAAGCAAACACACACACACAGGGTACGATTACAGATTACAGATTACAAAAGCAAACACACACACACAGGGTACGATTACAGATTACAGATTACAAAAGCAAACACACACACACAGGGTACGATTACAGATTACAGATTACAAAAGCAAACACACACACACAGGGTACGATTACAGATTACAGATTACAAAAGCAAACACACACACACAGGGTACGATTACAGATTACAGATTACAAAAGCAAACACACACACACAGGGTACGATTACAGATTACAGATTACAAAAGCAAACACACACACACAGGGTACGATTACAGATTACAGATTACAAAAGCAAACACACACACACAGGGTACGATTACAGATTACAGATTACAAAAGCAAACACACACACACAGGGTACGATTACAGATTACAGATTACAAAAGCAAACACACACACACAGGGTACGATTACAGATTACAGATTACAAAAGCAAACACACACACACAGGGTACGATTACAGATTACAGATTACAAAAGCAAACACACACACACAGGGTACGATTACAGATTACAGATTACAAAAGCAAACACACACACACAGGGTACGATTACAGATTACAGATTACAAAAGCAAACACACACACACAGGGTACGATTACAGATTACAGATTACAAAAGCAAACACACACACACAGGGTACGATTACAGATTACAGATTACAAAAGCAAACACACACACACAGGGTACGATTACAGATTACAGATTACAAAAGCAAACACACACACACAGGGTACGATTACAGATTACAGATTACAAAAGCAAACACACACACACAGGGTACGATTACAGATTACAGATTACAAAAGCAAACACACACACACAGGGTACGATTACAGATTACAGATTACAAAAGCAAACACACACACACAGGGTACGATTACAGATTACAGATTACAAAAGCAAACACACACACACAGGGTACGATTACAGATTACAGATTACAAAAGCAAACACACACACACAGGGTACGATTACAGATTACAGATTACAAAAGCAAACACACACACACAGGGTACGATTACAGATTACAGATTACAAAAGCAAACACACACACACAGGGTACGATTACAGATTACAGATTACAAAAGCAAACACACACACACAGGGTACGATTACAGATTACAGATTACAAAAGCAAACACACACACACAGGGTACGATTACAGATTACAGATTACAAAAGCAAACACACACACACAGGGTACGATTACAGATTACAGATTACAAAAGCAAACACACACACACAGGGTACGATTACAGATTACAGATTACAAAAGCAAACACACACACACAGGGTACGATTACAGATTACAGATTACAAAAGCAAACACACACACACAGGGTACGATTACAGATTACAGATTACAAAAGCAAACACACACACACAGGGTACGATTACAGATTACAGATTACAAAAGCAAACACACACACACAGGGTACGATTACAGATTACAGATTACAAAAGCAAACACACACACACAGGGTACGATTACAGATTACAGATTACAAAAGCAAACACACACACACAGGGTACGATTACAGATTACAGATTACAAAAGCAAACACACACACACAGGGTACGATTACAGATTACAGATTACAAAAGCAAACACACACACACAGGGTACGATTACAGATTACAGATTACAAAAGCAAACACACACACACAGGGTACGATTACAGATTACAGATTACAAAAGCAAACACACACACACAGGGTACGATTACAGATTACAGATTACAAAAGCAAACACACACACACAGGGTACGATTACAGATTACAGATTACAAAAGCAAACACACACACACAGGGTACGATTACAGATTACAGATTACAAAAGCAAACACACACACACAGGGTACGATTACAGATTACAGATTACAAAAGCAAACACACACACACAGGGTACGATTACAGATTACAGATTACAAAAGCAAACACACACACACAGGGTACGATTACAGATTACAGATTACAAAAGCAAACACACACACACAGGGTACGATTACAGATTACAGATTACAAAAGCAAACACACACACACAGGGTACGATTACAGATTACAGATTACAAAAGCAAACACACACACACAGGGTACGATTACAGATTACAGATTACAAAAGCAAACACACACACACAGGGTACGATTACAGATTACAGATTACAAAAGCAAACACACACACACAGGGTACGATTACAGATTACAGATTACAAAAGCAAACACACACACACAGGGTACGATTACAGATTACAGATTACAAAAGCAAACACACACACACAGGGTACGATTACAGATTACAGATTACAAAAGCAAACACACACACACAGGGTACGATTACAGATTACAGATTACAAAAGCAAACACACACACACAGGGTACGATTACAGATTACAGATTACAAAAGCAAACACACACACACAGGGTACGATTACAGATTACAGATTACAAAAGCAAACACACACACACAGGGTACGATTACAGATTACAGATTACAAAAGCAAACACACACACACAGGGTACGATTACAGATTACAGATTACAAAAGCAAACACACACACACAGGGT";
	//cout << palavra4 << " tamanho: " << palavra4.length() << endl;

	Nodo * raiz = new Nodo(palavra);


	//char * palavra2 = argv[2];
	cout << "Inserindo palavra " << palavra << endl;
	raiz->inserePalavra(palavra);
	cout << "Inserindo palavra " << palavra2 << endl;
	raiz->inserePalavra(palavra2);
	cout << "Inserindo palavra " << palavra3 << endl << endl;
	raiz->inserePalavra(palavra3);
	
	cout << "Removendo palavra " << palavra << endl;
	raiz->removePalavra(palavra);
	
	cout << (raiz->buscaPalavra(palavra) ? "" : "Não") << " Encontrou " << palavra << endl;
	cout << (raiz->buscaPalavra(palavra2) ? "" : "Não") << " Encontrou " << palavra2 << endl;
	cout << (raiz->buscaPalavra(palavra3) ? "" : "Não") << " Encontrou " << palavra3 << endl << endl;
	//cout << (raiz->buscaPalavra(palavra4) ? "" : "Não") << " Encontrou " << palavra4 << endl;
	//cout << (raiz->buscaPalavra(palavra5) ? "" : "Não") << " Encontrou " << palavra5 << endl;
	
	cout << "Removendo palavra " << palavra2 << endl;
	raiz->removePalavra(palavra2);

	cout << "Removendo palavra " << palavra3 << endl;
	raiz->removePalavra(palavra3);

	cout << (raiz->buscaPalavra(palavra3) ? "" : "Não") << " Encontrou " << palavra3 << endl;
	cout << (raiz->buscaPalavra(palavra2) ? "" : "Não") << " Encontrou " << palavra2 << endl;
	
	return 0;
}
